### ISSUE TITLE
feat: scoped styles

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/web-component-base#30]
Minimal solution for scoped styles: pass a `Partial<CSSStyleDeclaration>` object to a `[style]` attribute that our `createElement` function will spread as style of the created element.

for CSSStyleDeclaration reference: https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration

**Comment by ayoayco** [comment]
See this example component with a coupe of style objects. We should be able to rewrite this to use the new `[style]` we will implement in this issue. 

https://github.com/ayoayco/web-component-base/blob/main/site/src/components/feature-set.js

**Comment by ayoayco** [comment]
Maybe the square brackets is unnecessary

**Comment by ayoayco** [comment]
Maybe I don’t have to implement this, if something like StyleX already exists? 🙃 https://stylexjs.com/docs/learn/

**Comment by beatzball** [comment]
> Maybe I don’t have to implement this, if something like StyleX already exists? 🙃 https://stylexjs.com/docs/learn/
> 
> 
> But I think they need a bundler?

On their site:

```
The recommended way to use StyleX in development and production is with the build-time compiler.
```

https://stylexjs.com/docs/learn/installation/

**Comment by ayoayco** [comment]
TIL this is a basic pattern in reactjs: https://www.digitalocean.com/community/tutorials/how-to-style-react-components

I now think enabling this using just the `style` attribute is a good design since we already have a JSX-like syntax.
